In [5]:
from bs4 import BeautifulSoup
import requests

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

#Define a custom User-Agent in a headers dictionary
headers = {'User-Agent': 'MyWebScraper/1.0 (your_email@example.com)'}

#Pass the headers to the request
page = requests.get(url , headers = headers)

soup = BeautifulSoup(page.text, 'html')

In [ ]:
soup.find_all('table')[1]

In [ ]:
soup.find('table')

In [6]:
table = soup.find('table', class_ = 'wikitable sortable')

In [7]:
world_titles = table.find_all('th')

In [8]:
print(world_titles)

[<th id="mwPw">Rank</th>, <th id="mwQA">Name</th>, <th id="mwQQ">Industry</th>, <th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>, <th id="mwRA">Revenue growth</th>, <th id="mwRQ">Employees</th>, <th id="mwRg">Headquarters</th>]

In [9]:
world_table_titles = [title.text.strip() for title in world_titles]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [10]:
import pandas as pd

df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [12]:
column_data = table.find_all('tr')

In [13]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [14]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [15]:
df.to_csv(r'C:\Users\phyop\OneDrive\Desktop\Data Analytic\Portfolio\Output Folder from Web Scraping\us-largest-companies.csv', index = False)